server:
  port: 8040

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              spring.json.trusted.packages: '*'
        binder:
          brokers: localhost:9092
      function:
        bindings:
          processor-in-0: security-review-source
          processor-out-0: security-review-destination
